### ISSUE TITLE
Add new description while keeping the old one 

### ISSUE THREAD

**Issue by Louishb** [madebyfabian/figma-plugin-bunch-description-change#1]
Hi, thanks for making this plugin! Been praying someone would.

i'm just wondering if it would be possible to add a new description while keeping the current one?

At the moment it overwrites whatever is currently in the description.

**Comment by madebyfabian** [comment]
Hey :) Thanks for reaching out! Glad that you like it and it found the way to a user like you that actually needs it :P

Sure, that's possible! Just switch "RegEx" on, and type `.*` into the "Match" field. This will match the whole current description. Then, next to the "Change to" field, you can just hit the "Current match" button. Now you have your current description, and you can add something to it. I'll made an example: 
![image](https://user-images.githubusercontent.com/32813692/78968320-7a4a5980-7b04-11ea-8a49-5f35268ada9d.png)

Of course, this is not the nicest solution, I know :) Maybe I'll add some UI buttons in the future.

**Comment by madebyfabian** [comment]
Hey :) So I updated the plugin - now it works without regex! You now can just click "current description" and it will take the current description and you can add something to it. 
Cheers
