### ISSUE TITLE
Change descriptions of color/text styles

### ISSUE THREAD

**Issue by 54nn0n** [madebyfabian/figma-plugin-bunch-description-change#12]
This would be so neat if this plugin could include descriptions of color styles and text styles too!

**Comment by madebyfabian** [comment]
@54nn0n Hi there, thanks for suggesting. I get this request very often and though there are better plugins to manage styles, I will check if I can implement that in my plugin too. Should be not too much of a deal.

**Comment by madebyfabian** [comment]
@54nn0n Hi there, I have implemented this feature, it's now live in the community. Just reload your Figma File and you can use it. I have also rebuilt the plugin in vue 3 & vite and rebuilt the styles to support dark mode. 🚀
Let me know if it works like intended.

**Comment by madebyfabian** [comment]
Here is the code if interested: https://github.com/madebyfabian/figma-plugin-bunch-description-change/commit/e929cd4609df8abe58d3159fbbd7eb245b3cc94f
